In [9]:
import numpy as np

#Effort Estimation
X= np.array(([200,5,10],[150,6,15],[600,3,14]), dtype=float) #Line of code, Cyclomatic complexity and function calls
Y=np.array(([10],[13],[12]), dtype=float) #Man hours

X= X/np.amax(X, axis=0)
Y= Y/100

In [12]:
class NeuralNetwork(object):
    def __init__(self):
        self.inputSize=3
        self.hiddenSize=3
        self.outputSize=1

        self.a=0

        self.W1= np.random.randn(self.inputSize, self.hiddenSize) 
        self.W2= np.random.randn(self.hiddenSize, self.outputSize) 

        self.B1= np.random.randn(1,self.hiddenSize) 
        self.B2= np.random.randn(1,self.outputSize) 

    def feedForward(self,X):
        self.layer1= np.dot(X,self.W1)+ self.B1
        self.layer1Act= self.sigmoid(self.layer1) 
        self.outputLayer= np.dot(self.layer1Act, self.W2)+ self.B2
        output= self.sigmoid(self.outputLayer)
        return output

    def sigmoid(self, x, deriv=False):
        if (deriv==True):
            return x* (1-x)
        return 1/(1+np.exp(-x))

    def backPass(self, X, y, output,learningRate):
        self.outputError= (y- output)/2
        self.outputDelta= self.outputError* self.sigmoid(output, deriv=True)

        self.layer1ActError= self.outputDelta.dot(self.W2.T) 
        self.layer1ActDelta= learningRate*self.layer1ActError* self.sigmoid(self.layer1Act, deriv=True)

        self.W1+= X.T.dot(self.layer1ActDelta)
        self.W2+= self.layer1Act.T.dot(self.outputDelta)

    def training(self,X,Y,learningRate):
        output=self.feedForward(X)
        self.loss=Y-output

        if (self.a %100==0): 
            print("Loss at "+str(self.a)+" iteration: \n"+str(self.loss))

        self.backPass(X,Y, output,learningRate)
        self.a+=1

    def start(self,n,learningRate):
        for i in range(n):
        	self.training(X,Y,learningRate)



if __name__ == "__main__":
    neuralNetwork=NeuralNetwork()
    neuralNetwork.start(1000,0.05) 
    print("Input values are: \n",X )
    print("Actual output: \n",Y)
    print("Output after prediction: \n",neuralNetwork.feedForward(X))

Loss at 0 iteration: 
[[-0.19302384]
 [-0.13983911]
 [-0.26147922]]
Loss at 100 iteration: 
[[-0.01382027]
 [ 0.02732423]
 [-0.01891136]]
Loss at 200 iteration: 
[[-0.01145079]
 [ 0.02893928]
 [-0.01260274]]
Loss at 300 iteration: 
[[-0.01217544]
 [ 0.0277597 ]
 [-0.01074721]]
Loss at 400 iteration: 
[[-0.01302888]
 [ 0.02650469]
 [-0.00935579]]
Loss at 500 iteration: 
[[-0.01379015]
 [ 0.02537573]
 [-0.00811078]]
Loss at 600 iteration: 
[[-0.01445482]
 [ 0.02437431]
 [-0.00697934]]
Loss at 700 iteration: 
[[-0.01503487]
 [ 0.02348657]
 [-0.0059518 ]]
Loss at 800 iteration: 
[[-0.01554189]
 [ 0.02269899]
 [-0.00502025]]
Loss at 900 iteration: 
[[-0.01598587]
 [ 0.02199958]
 [-0.00417697]]
Input values are: 
 [[0.33333333 0.83333333 0.66666667]
 [0.25       1.         1.        ]
 [1.         0.5        0.93333333]]
Actual output: 
 [[0.1 ]
 [0.13]
 [0.12]]
Output after prediction: 
 [[0.11637536]
 [0.10862218]
 [0.12341447]]
